### PR TITLE
chore: `sc-sast scan start --sargs` scaRuntimeArguments support added

### PR DESCRIPTION
**Pull request by gendry-gh**
#198 
#449 

The added fcli `--sargs --sca-args` option allows specify scan args along with other arguments such as -filter ([see accepted arguments]( https://www.microfocus.com/documentation/fortify-software-security-center/2320/SC_SAST_Help_23.2.0/index.htm#cli/sargs-options.htm?TocPath=Fortify%2520ScanCentral%2520SAST%2520Command-Line%2520Options%257C_____12))

As of --targs, with current fcli support, there is no need for it.
Currently, we can only start a sast scan using package or mbs. These two options do not support/requires translation arguments (targs are passed to the `scancentral package` cmd, and mbs are already translated)

### CODE REVIEW

**Comment by rsenden** [comment]
We'd need to double-check exact SC SAST behavior with regards to interaction between `-sargs` and the `-filter`, `-rules` and `--project-template` options on the `scancentral start` command. These dedicated options are used to include a local filter file, rules file or project template into the scan payload; not sure what happens if you specify something like `-sargs -filter myfilter.txt` without specifying the `-filter` option (would that expect the specified file to be available on the sensor?), or if for example `-filter myfilter.txt` automatically adds the corresponding scan argument.

**Comment by Andhrei** [comment]
[The documentation](https://www.microfocus.com/documentation/fortify-software-security-center/2320/SC_SAST_Help_23.2.0/index.htm#cli/sargs-options.htm?TocPath=Fortify%2520ScanCentral%2520SAST%2520Command-Line%2520Options%257C_____12) lists the supported options :

image

**Comment by Andhrei** [comment]
I just checked, for `-filters filter.txt` scancentral client adds the filter.txt in the zip payload : 
image

And it does so for both cmds : 
- `scancentral start [...] -filters filter.txt`
- `scancentral start [...] -sargs "-filters filter.txt"`

As FCLI doesn't package right now, do we want to do the same ? or (for now) let the user insert the required filters/custom rules files in the zip, along with the right `-sargs`

**Comment by rsenden** [comment]
ScanCentral expects the package.zip file inside another zip file (which is created by fcli on the fly); I guess these extra filer/template/rule files go into the outer zip file, not the zip-file created by `scancentral package` command.

**Comment by Andhrei** [comment]
indeed.

What about adding an `--include-file rule.xml` option to insert a file in the outer zip ?

**Comment by rsenden** [comment]
Superseded by #627, which adds support for including local files in scan payload.

**Pull request closed without merging**
